name: Backend CI

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:

permissions:
  contents: read

jobs:
  workflow_check:
    name: Backend workflow check
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js 
        uses: actions/setup-node@v4 
        with: 
          node-version: 22 
          cache: npm 
          cache-dependency-path: package-lock.json

      - name: Install depenencies 
        run: npm ci 

      - name: Lint
        run: npm run lint

      - name: Run automated tests 
        run: npm test 

      - name: Build
        run: npm run build

      - name: Confirm workflow is running 
        run: echo "Backend Github Actions workflow is running successfully."
